"""empty message

Revision ID: 13309aa765b0
Revises: ad571655b402
Create Date: 2020-09-10 19:45:57.903040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13309aa765b0'
down_revision = 'ad571655b402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipemnt_puton_applications', schema=None) as batch_op:
        batch_op.drop_column('usage')

    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.drop_column('return_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('return_time', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('equipemnt_puton_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
