"""empty message

Revision ID: 21d2f6f706e3
Revises: 2cb50a35c8b1
Create Date: 2020-09-09 23:57:30.122652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d2f6f706e3'
down_revision = '2cb50a35c8b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
