"""empty message

Revision ID: 4eff4f6c6710
Revises: 49acc0bdf9bc
Create Date: 2020-09-12 09:40:40.061272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4eff4f6c6710'
down_revision = '49acc0bdf9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.String(length=128), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('message_time', sa.DateTime(), nullable=True),
    sa.Column('isRead', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('fk_messages_receiver_id_users')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_column('log_time')

    op.drop_table('messages')
    # ### end Alembic commands ###
