"""empty message

Revision ID: ad571655b402
Revises: 21d2f6f706e3
Create Date: 2020-09-10 15:19:02.926603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad571655b402'
down_revision = '21d2f6f706e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lender_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('review_time', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lender_applications', schema=None) as batch_op:
        batch_op.drop_column('review_time')
        batch_op.drop_column('application_time')

    # ### end Alembic commands ###
